export const ideaCategories = [
  { id: 0, name: 'Ẩm thực' },
  { id: 1, name: 'Giáo dục' },
  { id: 2, name: 'Công nghệ' },
  { id: 3, name: 'Y tế' },
  { id: 4, name: 'Môi trường' },
  { id: 5, name: 'Giải trí' },
  { id: 6, name: 'Kinh doanh' },
  { id: 7, name: 'Du lịch & Dịch vụ' },
  { id: 8, name: 'Thể thao' },
  { id: 9, name: 'Nông nghiệp' },
  { id: 10, name: 'Thời trang' },
  { id: 11, name: 'Tâm lý' },
  { id: 12, name: 'Nghệ thuật' },
  { id: 13, name: 'Phát triển phần mềm' },
  { id: 14, name: 'Tài chính & Đầu tư' },
];

export const DCardIdea = [
  {
    id: 2,
    imageUrl: '/thumbnail/climate-change.jpg',
    category: 'Môi trường',
    title: 'Chế tạo kệ bằng nhạc cụ từ các nhạc phẩm tái chế',
    desc: 'Bạn có thể tái chế, trang trí cây đàn ghita, piano thành những chiếc kệ gỗ, kệ sách trưng bày ấn tượng.',
    author: 'Lê Viết Tuấn',
    views: 80,
    publishDate: '25/01/2025',
  },

  {
    id: 1,
    imageUrl: '/thumbnail/digital-transformation.jpg',
    category: 'Nông nghiệp',
    title: 'Phương pháp giảm sâu bọ cho cây trồng ban đêm',
    desc: 'Giải pháp hiệu quả giúp bảo vệ cây trồng khỏi sâu bọ vào ban đêm một cách an toàn và bền vững.',
    author: 'Trần Bảo Anh Huy',
    views: 12,
    publishDate: '25/01/2025',
  },
  {
    id: 4,
    imageUrl: '/thumbnail/start-up.jpg',
    category: 'Nông nghiệp',
    title: 'Phương pháp giảm sâu bọ cho cây trồng ban đêm',
    desc: 'Giải pháp hiệu quả giúp bảo vệ cây trồng khỏi sâu bọ vào ban đêm một cách an toàn và bền vững.',
    author: 'Trần Bảo Anh Huy',
    views: 12,
    publishDate: '25/01/2025',
  },

  {
    id: 3,
    imageUrl: '/thumbnail/climate-change.jpg',
    category: 'Môi trường',
    title: 'Chế tạo kệ bằng nhạc cụ từ các nhạc phẩm tái chế',
    desc: 'Bạn có thể tái chế, trang trí cây đàn ghita, piano thành những chiếc kệ gỗ, kệ sách trưng bày ấn tượng.',
    author: 'Lê Viết Tuấn',
    views: 80,
    publishDate: '25/01/2025',
  },

  {
    id: 5,
    imageUrl: '/thumbnail/digital-transformation.jpg',
    category: 'Nông nghiệp',
    title: 'Phương pháp giảm sâu bọ cho cây trồng ban đêm',
    desc: 'Giải pháp hiệu quả giúp bảo vệ cây trồng khỏi sâu bọ vào ban đêm một cách an toàn và bền vững.',
    author: 'Trần Bảo Anh Huy',
    views: 12,
    publishDate: '25/01/2025',
  },
  {
    id: 6,
    imageUrl: '/thumbnail/start-up.jpg',
    category: 'Nông nghiệp',
    title: 'Phương pháp giảm sâu bọ cho cây trồng ban đêm',
    desc: 'Giải pháp hiệu quả giúp bảo vệ cây trồng khỏi sâu bọ vào ban đêm một cách an toàn và bền vững.',
    author: 'Trần Bảo Anh Huy',
    views: 12,
    publishDate: '25/01/2025',
  },
];
